version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: hummingbot_server_1
      APP_PORT: 8080

  server:
    build:
      context: https://github.com/sanduber/hummingbot.git
      dockerfile: Dockerfile
    user: "1000:1000"
    init: true
    ports:
      - "8080:8080"
    volumes:
      - ./conf:/conf
      - ./logs:/logs
      - ./data:/data
    environment:
      - CONFIG_FILE=config.yml
      - STRATEGY=arbitrage
